version: '3.4'

services:
  frontend.web:
    image: ${DOCKER_REGISTRY-}frontendweb
    build:
      context: .\FrontEnd.Web
      dockerfile: Dockerfile

  backend.web:
    image: ${DOCKER_REGISTRY-}backendweb
    build:
      context: .\BackEnd.Web
      dockerfile: Dockerfile
